### ISSUE TITLE
Faciliter les développements en intégration/dev pour les API France Connectées

### ISSUE THREAD

**Issue by guillett** [etalab/siade_staging_data#15]
Je trouve l'expérience de développement des API France Connectées assez laborieuse.

En effet, @skelz0r disait [sur Mattermost](https://mattermost.incubateur.net/betagouv/pl/bsnexoq7jfy1xra3xhe51ebdrr)

> [...] il n'est techniquement pas possible de faire des tests E2E pour le moment (car il faudrait accorder les données de tests de FC avec des potentiels données de tests pour chaque FD, ce qui est compliqué et pas forcément adapté à tout le monde).

La chance qu'on a en dev sur FC c'est que clientID et clientSecret [sont publics](https://partenaires.franceconnect.gouv.fr/fcp/fournisseur-service) et donc les subs sont partagé avec tout le monde.

Plutôt que de passer par le token `mesri` (ou [`cnous`](https://github.com/etalab/siade_staging_data#cas-de-franceconnect)), est ce qu'il serait possible de repliquer ce qui se passe en prod en se basant sur un dictionnaire dont les clés sur les `sub` de dev FC.

Par exemple pour ['Angela Claire Louise DUBOIS'](https://github.com/france-connect/identity-provider-example/blob/master/database.csv#L2) de FC, dont le `sub` est `b6048e95bb134ec5b1d1e1fa69f287172e91722b9354d637a1bcf2ebb0fd2ef5v1` (pour le clientID/Secret public), on pourrait faire correspondre un payload donné pour les API France Connectées que vous gérez. Par exemple, pour `api-statut-etudiant` :

```json
{
   "dateNaissance" : "1962-08-24",
   "ine" : "1234567890T",
   "inscriptions" : [
      {
         "codeCommune" : "33063",
         "dateDebutInscription" : "2020-07-01",
         "dateFinInscription" : "2021-08-31",
         "etablissement" : {
            "nomEtablissement" : "LYCEE GENERAL ET TECHNOLOGIQUE CAMILLE JULLIAN",
            "uai" : "0330023W"
         },
         "regime" : "formation initiale",
         "statut" : "inscrit"
      }
   ],
   "nomFamille" : "DUBOIS",
   "prenom" : "Angela"
}
```

On peut envisager un ou plusieurs fichiers yaml. Par exemple, avec un seul fichier, il pourrait ressembler à ça

```yaml
---
b6048e95bb134ec5b1d1e1fa69f287172e91722b9354d637a1bcf2ebb0fd2ef5v1:
  mesri:
    dateNaissance: '1962-08-24'
    ine: 1234567890T
    inscriptions:
    - codeCommune: '33063'
      dateDebutInscription: '2020-07-01'
      dateFinInscription: '2021-08-31'
      etablissement:
        nomEtablissement: LYCEE GENERAL ET TECHNOLOGIQUE CAMILLE JULLIAN
        uai: 0330023W
      regime: formation initiale
      statut: inscrit
    nomFamille: DUBOIS
    prenom: Angela
```

Où `b6048e95bb134ec5b1d1e1fa69f287172e91722b9354d637a1bcf2ebb0fd2ef5v1` est donc le `sub`. `sub` récupérable par un appel à `${fcRoot}/api/v1/userinfo?schema=openid` et dans le JWT du champ `id_token`. Par exemple 

```jwt
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2ZjcC5pbnRlZzAxLmRldi1mcmFuY2Vjb25uZWN0LmZyIiwic3ViIjoiYjYwNDhlOTViYjEzNGVjNWIxZDFlMWZhNjlmMjg3MTcyZTkxNzIyYjkzNTRkNjM3YTFiY2YyZWJiMGZkMmVmNXYxIiwiYXVkIjoiMjExMjg2NDMzZTM5Y2NlMDFkYjQ0OGQ4MDE4MWJkZmQwMDU1NTRiMTljZDUxYjNmZTc5NDNmNmIzYjg2YWI2ZSIsImV4cCI6MTY4MTk5NzEyOCwiaWF0IjoxNjgxOTk3MDY4LCJub25jZSI6InRwSHdrS0ZONm00dkMwYkRmN1dndVVkMDRlLU9LOHZaeUhXWmZzSTExY3N6VUZxQmFLNG1yQkhVZ1dScW92MVQiLCJpZHAiOiJGQyIsImFjciI6ImVpZGFzMSIsImFtciI6bnVsbH0.g2B22UYDm3HN_6N5UxDhq_Uc-NFTeKV4qvDitKuBLAc'
```

et dont le contenu est 
```json
{
  "iss": "https://fcp.integ01.dev-franceconnect.fr",
  "sub": "b6048e95bb134ec5b1d1e1fa69f287172e91722b9354d637a1bcf2ebb0fd2ef5v1",
  "aud": "211286433e39cce01db448d80181bdfd005554b19cd51b3fe7943f6b3b86ab6e",
  "exp": 1681997128,
  "iat": 1681997068,
  "nonce": "tpHwkKFN6m4vC0bDf7WguUd04e-OK8vZyHWZfsI11cszUFqBaK4mrBHUgWRqov1T",
  "idp": "FC",
  "acr": "eidas1",
  "amr": null
}
```

(signé avec le clientSecret d'ailleurs mais on s'en fiche un peu ici).
